### ISSUE TITLE
关于Figure 2的对应代码疑问

### ISSUE THREAD

**Issue by 2016WUJI01** [ACAT-SCUT/CycleNet#2]
恭喜团队获得如此成功的成绩，有幸拜读论文和代码，但是对与Figure 2的对应代码存在相关疑问：
对于此方法的如何做对sin/cos等循环变量的生成？LINK：[self.cycleQueue](https://github.com/2016WUJI01/CycleNet/blob/c867d48f0794d73636529c33efc50961f1b5e857/models/CycleNet.py#L61)

**Comment by lss-1138** [comment]
您好。
这个循环变量是可学习参数，形状为（cycle_len, channel_size），在这里[生成](https://github.com/ACAT-SCUT/CycleNet/blob/c867d48f0794d73636529c33efc50961f1b5e857/models/CycleNet.py#L9)。
它一开始是初始化为全0，也就是一条直线。经过训练后，会自己学习到每个通道自己的循环周期模式，也就是Figure 4对应的有意义的曲线。

**Comment by 2016WUJI01** [comment]
感谢回答！
那我一开始的理解还是有一定错误的，理解成需要固定的周期函数（sin/cos）了 :(
