### ISSUE TITLE
Missing Solar-Energy Datasets

### ISSUE THREAD

**Issue by CCMKCCMK** [ACAT-SCUT/CycleNet#5]
Hi, I am trying to reproduce this impressive work, but I couldn't find the Solar-Energy dataset from the google drive.
![image](https://github.com/user-attachments/assets/d7d3ba18-320e-4a00-bc09-a6e5eb445451)
I also checked the dataset paper provided by Lai et al. 
[multivariate-time-series-data](https://github.com/laiguokun/multivariate-time-series-data)
but their dataset seems having different rows and columns.

Although I can rebuild the datasets, but I am not sure if that will be the same as yours.

So would you mind to publish your Solar-Energy dataset again?
Thanks for your help!

**Comment by lss-1138** [comment]
Hello, thank you for pointing this out!
The Solar-Energy dataset we used is the same as the one used by iTransformer and SCINet, which indeed was not included in the previous link.
For convenience, we have released a **new dataset link** that includes all commonly used datasets, including the Solar-Energy and PEMS datasets. 
https://drive.google.com/file/d/1bNbw1y8VYp-8pkRTqbjoW-TA-G8T0EQf/view
![image](https://github.com/user-attachments/assets/63473211-f436-4337-896f-377e4270f5ff)

**Comment by CCMKCCMK** [comment]
We have tested the [Electricity_96_96_CycleNet_custom_ftM_sl96_pl96_cycle168_linear_seed2024](https://github.com/ACAT-SCUT/CycleNet/tree/main/checkpoints/Electricity_96_96_CycleNet_custom_ftM_sl96_pl96_cycle168_linear_seed2024) checkpoint by setting the `is_training 0` in the scripts/CycleNet/Linear-Input-96/electricity.sh file:
![image](https://github.com/user-attachments/assets/81d9c6eb-6417-4495-8174-6ad766cd0b36)

However, we get some error which seems to related to the mismatch between dataset and the model:
``` bash
x = x - self.cycleQueue(cycle_index, self.seq_len)
RuntimeError: The size of tensor a (320) must match the size of tensor b (321) at non-singleton dimension 2
```

We tried to reduce `enc_in 321` to `enc_in 320` to match your data:
![image](https://github.com/user-attachments/assets/0cf935d4-ce47-4fed-9e71-c3ba6f56957a)

But seems the model is indeed trained on `enc_in 321` and didn't accept that parameter:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/088fcfa8-a6a1-4bed-93e6-e9f69b17f80f">

So we wander what's happening (maybe the dataset is not the correct one?) and ask you for help to reproduce the results!
