### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by ZhangHY-416** [ACAT-SCUT/CycleNet#6]
I downloaded the ZIP file and set up the torch environment. Which file should I run next? I'm using PyCharm.
![Uploading 屏幕截图 2024-11-28 210718.png…]()

**Comment by lss-1138** [comment]
Your image seems to have not uploaded successfully, I can't see it here. You can open a new terminal window in PyCharm and run the command `sh run_main.sh` to execute it.
