### ISSUE TITLE
关于Cycle_index的疑问

### ISSUE THREAD

**Issue by SpriteWithoutIce** [ACAT-SCUT/CycleNet#8]
恭喜获得如此好的成绩，有幸拜读论文和代码，有一些疑问，希望可以帮忙解答一下，多谢
`gather_index = (index.view(-1, 1) + torch.arange(length, device=index.device).view(1, -1)) % self.cycle_len`
`cycle_index = torch.tensor(self.cycle_index[s_end])`
包括图Figure3，看起来是从当前位置t向后取了seq_len个点的cycle_index 作为[t-seq_len, t]的周期项，我理解的周期项是从序列开始的绝对位置对齐的，所以有一些疑问，为什么不是从[t-seq_len, t]取cycle_index作为周期项呢，也就是这里为什么不写成`cycle_index = torch.tensor(self.cycle_index[s_begin])`呢？

**Comment by lss-1138** [comment]
Hello，感谢对我们工作的关注

这用s_end而不是s_begin，是为了对应data_loeader里的
self.cycle_index = (np.arange(len(data)) % self.cycle)[border1:border2]和seq_x = self.data_x[s_begin:s_end]
用s_begin的话，会超出这里的边界条件[border1:border2]。所以这里是没问题的。


造成你的疑惑点可能在于：
x = x - self.cycleQueue(**cycle_index**, self.seq_len)

如果要跟Figure 3完全对应的话，这里应该是：
x = x - self.cycleQueue(**cycle_index-self.seq_len**, self.seq_len)

但cycle_index只是一个**相对位置索引**的概念，不管是cycle_index还是cycle_index-self.seq_len，逻辑上是等价的，只是学出来的曲线会有左右偏移。

对于这一点，我看知乎的博主解释的挺好的，可以参考：

![image](https://github.com/user-attachments/assets/886a8782-b878-4209-9042-fa2e5888d634)

（2024 NIPS）CycleNet: Enhancing Time Series Forecasting through Modeling Periodic Patterns - 的泼墨佛给克呢的文章 - 知乎
https://zhuanlan.zhihu.com/p/778345073

**Comment by SpriteWithoutIce** [comment]
感谢解答！
